<?php

namespace Database\Seeders;

use App\Models\Divisi;
use Illuminate\Database\Seeder;

class DivisiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $collections = [
            ['unit_kerja_id' => 364, 'nama_divisi' => 'Divisi Transaksi Pinjaman'],
            ['unit_kerja_id' => 364, 'nama_divisi' => 'Divisi Legal & Administrasi Pinjaman'],
            ['unit_kerja_id' => 332, 'nama_divisi' => 'Divisi Hubungan Bisnis Korporasi Non BUMD'],
            ['unit_kerja_id' => 364, 'nama_divisi' => 'Divisi Data & Dokumen Pinjaman'],
            ['unit_kerja_id' => 641, 'nama_divisi' => 'Divisi Kebijakan Non Bisnis'],
            ['unit_kerja_id' => 236, 'nama_divisi' => 'Divisi Sistem Akuntansi'],
            ['unit_kerja_id' => 351, 'nama_divisi' => 'Divisi Kredit Kepemilikan Rumah'],
            ['unit_kerja_id' => 639, 'nama_divisi' => 'Divisi Kredit Mikro II'],
            ['unit_kerja_id' => 236, 'nama_divisi' => 'Divisi Keuangan & Pelaporan'],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Manajemen Audit'],
            ['unit_kerja_id' => 642, 'nama_divisi' => 'Divisi Audit Umum'],
            ['unit_kerja_id' => 388, 'nama_divisi' => 'Kantor Kas Tropodo'],
            ['unit_kerja_id' => 244, 'nama_divisi' => 'Divisi Branchless Banking'],
            ['unit_kerja_id' => 642, 'nama_divisi' => 'Divisi Audit Teknologi Informasi'],
            ['unit_kerja_id' => 244, 'nama_divisi' => 'Divisi Cash & Trade Operation'],
            ['unit_kerja_id' => 642, 'nama_divisi' => 'Divisi Audit Investigasi & Anti Fraud'],
            ['unit_kerja_id' => 636, 'nama_divisi' => 'Divisi Digital Banking'],
            ['unit_kerja_id' => 636, 'nama_divisi' => 'Divisi Digital Banking Ecosystem'],
            ['unit_kerja_id' => 332, 'nama_divisi' => 'Divisi Hubungan Pemerintah Provinsi DKI Jakarta'],
            ['unit_kerja_id' => 637, 'nama_divisi' => 'Divisi Pengadaan TI'],
            ['unit_kerja_id' => 332, 'nama_divisi' => 'Divisi Hubungan Bisnis Ekosistem BUMD'],
            ['unit_kerja_id' => 332, 'nama_divisi' => 'Divisi Hubungan Bisnis Korporasi Non BUMD'],
            ['unit_kerja_id' => 232, 'nama_divisi' => 'Divisi Litigasi'],
            ['unit_kerja_id' => 355, 'nama_divisi' => 'Divisi Manajemen Kinerja & Project Management Office'],
            ['unit_kerja_id' => 232, 'nama_divisi' => 'Divisi Hukum Korporasi & Perkreditan'],
            ['unit_kerja_id' => 640, 'nama_divisi' => 'Divisi Kebijakan Bisnis'],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Konsumer'],
            ['unit_kerja_id' => 357, 'nama_divisi' => 'Divisi Risiko Kredit/Pembiayaan Ritel'],
            ['unit_kerja_id' => 233, 'nama_divisi' => 'Divisi Tata Kelola & APU-PPT'],
            ['unit_kerja_id' => 72, 'nama_divisi' => 'Divisi Operasional Manajemen SDM'],
            ['unit_kerja_id' => 233, 'nama_divisi' => 'Divisi Review Kepatuhan'],
            ['unit_kerja_id' => 640, 'nama_divisi' => 'Divisi Kredit Komersial'],
            ['unit_kerja_id' => 351, 'nama_divisi' => 'Divisi Kredit Multi guna'],
            ['unit_kerja_id' => 66, 'nama_divisi' => 'Divisi Dana & Jasa'],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Project Management'],
            ['unit_kerja_id' => 639, 'nama_divisi' => 'Divisi Kredit Mikro II'],
            ['unit_kerja_id' => 638, 'nama_divisi' => 'Divisi Kredit Ritel I'],
            ['unit_kerja_id' => 638, 'nama_divisi' => 'Divisi Kredit Ritel II'],
            ['unit_kerja_id' => 99, 'nama_divisi' => 'Divisi Risiko Operasional'],
            ['unit_kerja_id' => 99, 'nama_divisi' => 'Divisi Risiko Kredit'],
            ['unit_kerja_id' => 244, 'nama_divisi' => 'Divisi Customer Care'],
            ['unit_kerja_id' => 244, 'nama_divisi' => 'Divisi Cash Pooling Center'],
            ['unit_kerja_id' => 636, 'nama_divisi' => 'Divisi Pengelolaan Aset dan Layanan Umum'],
            ['unit_kerja_id' => 637, 'nama_divisi' => 'Divisi Pengadaan Non-TI'],
            ['unit_kerja_id' => 637, 'nama_divisi' => 'Divisi Pengadaan TI'],
            ['unit_kerja_id' => 243, 'nama_divisi' => 'Divisi Bisnis Cabang'],
            ['unit_kerja_id' => 243, 'nama_divisi' => 'Divisi Layanan Cabang'],
            ['unit_kerja_id' => 243, 'nama_divisi' => 'Divisi Pendukung Cabang'],
            ['unit_kerja_id' => 243, 'nama_divisi' => 'Divisi Jaringan Kantor'],
            ['unit_kerja_id' => 365, 'nama_divisi' => 'Divisi Pengelolaan Produk & Portofolio'],
            ['unit_kerja_id' => 365, 'nama_divisi' => 'Divisi Bisnis Dana Ritel & Komunitas'],
            ['unit_kerja_id' => 365, 'nama_divisi' => 'Divisi Transaction Banking'],
            ['unit_kerja_id' => 355, 'nama_divisi' => 'Divisi Perencanaan & Pengembangan'],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Menengah'],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Konsumer'],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Lelang & Portfolio Management'],
            ['unit_kerja_id' => 357, 'nama_divisi' => 'Divisi Risiko Kredit/Pembiayaan Menengah & Komersial I'],
            ['unit_kerja_id' => 72, 'nama_divisi' => 'Divisi Learning Center'],
            ['unit_kerja_id' => 72, 'nama_divisi' => 'Divisi Strategi & Kebijakan Manajemen SDM'],
            ['unit_kerja_id' => 72, 'nama_divisi' => 'Divisi Pengembangan & Budaya'],
            ['unit_kerja_id' => 66, 'nama_divisi' => 'Divisi Pembiayaan Menengah'],
            ['unit_kerja_id' => 66, 'nama_divisi' => 'Divisi Pembiayaan Konsumer'],
            ['unit_kerja_id' => 66, 'nama_divisi' => 'Divisi Pembiayaan Mikro & Ritel'],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Development'],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Operation'],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Governance'],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Business Analyst'],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Project Management'],
            ['unit_kerja_id' => 69, 'nama_divisi' => 'Divisi Banking Management dan ALMA'],
            ['unit_kerja_id' => 69, 'nama_divisi' => 'Divisi Global Market'],
            ['unit_kerja_id' => 359, 'nama_divisi' => 'Divisi Kesekretariatan'],
            ['unit_kerja_id' => 359, 'nama_divisi' => 'Divisi Komunikasi Pemasaran'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah'],
        ];

        collect($collections)->each(function ($data) {
            Divisi::create($data);
        });
    }
}
