<?php

namespace Database\Seeders;

use App\Models\UnitKerja;
use Illuminate\Database\Seeder;

class UnitKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $collections = [
            ['id_unit_kerja' => 21, 'nama' => 'Dana Pensiun Bank DKI'],
            ['id_unit_kerja' => 219, 'nama' => 'Dewan Pengawas Syariah'],
            ['id_unit_kerja' => 17, 'nama' => 'Direksi'],
            ['id_unit_kerja' => 364, 'nama' => 'Grup Administrasi Kredit & Pembiayaan'],
            ['id_unit_kerja' => 236, 'nama' => 'Grup Akuntansi & Keuangan'],
            ['id_unit_kerja' => 634, 'nama' => 'Grup Audit Internal'],
            ['id_unit_kerja' => 635, 'nama' => 'Grup Bisnis Digital'],
            ['id_unit_kerja' => 332, 'nama' => 'Grup Hubungan Kelembagaan'],
            ['id_unit_kerja' => 232, 'nama' => 'Grup Hukum'],
            ['id_unit_kerja' => 640, 'nama' => 'Grup Kebijakan & Prosedur'],
            ['id_unit_kerja' => 233, 'nama' => 'Grup Kepatuhan'],
            ['id_unit_kerja' => 639, 'nama' => 'Grup Kredit Komersial'],
            ['id_unit_kerja' => 351, 'nama' => 'Grup Kredit Konsumer'],
            ['id_unit_kerja' => 352, 'nama' => 'Grup Kredit Menengah'],
            ['id_unit_kerja' => 638, 'nama' => 'Grup Kredit Mikro'],
            ['id_unit_kerja' => 637, 'nama' => 'Grup Kredit Ritel'],
            ['id_unit_kerja' => 99, 'nama' => 'Grup Manajemen Risiko'],
            ['id_unit_kerja' => 244, 'nama' => 'Grup Operasional'],
            ['id_unit_kerja' => 636, 'nama' => 'Grup Pengadaan & Pengelolaan Aset'],
            ['id_unit_kerja' => 243, 'nama' => 'Grup Pengembangan Jaringan'],
            ['id_unit_kerja' => 365, 'nama' => 'Grup Penjualan Dana & Transaksional'],
            ['id_unit_kerja' => 355, 'nama' => 'Grup Perencanaan Strategis & Kinerja'],
            ['id_unit_kerja' => 633, 'nama' => 'Grup Restrukturisasi Kredit dan Penyelesaian Kredit Bermasalah'],
            ['id_unit_kerja' => 357, 'nama' => 'Grup Risiko Kredit'],
            ['id_unit_kerja' => 72, 'nama' => 'Grup Sumber Daya Manusia'],
            ['id_unit_kerja' => 66, 'nama' => 'Grup Syariah'],
            ['id_unit_kerja' => 358, 'nama' => 'Grup Teknologi Informasi'],
            ['id_unit_kerja' => 69, 'nama' => 'Grup Tresuri'],
            ['id_unit_kerja' => 390, 'nama' => 'Kantor Cabang Bandung'],
            ['id_unit_kerja' => 388, 'nama' => 'Kantor Cabang Gresik'],
            ['id_unit_kerja' => 378, 'nama' => 'Kantor Cabang Juanda'],
            ['id_unit_kerja' => 379, 'nama' => 'Kantor Cabang Kebayoran Baru'],
            ['id_unit_kerja' => 380, 'nama' => 'Kantor Cabang Matraman'],
            ['id_unit_kerja' => 381, 'nama' => 'Kantor Cabang Otista'],
            ['id_unit_kerja' => 392, 'nama' => 'Kantor Cabang Pembantu Abdul Muis'],
            ['id_unit_kerja' => 393, 'nama' => 'Kantor Cabang Pembantu Alam Sutera'],
            ['id_unit_kerja' => 394, 'nama' => 'Kantor Cabang Pembantu Ambengan'],
            ['id_unit_kerja' => 395, 'nama' => 'Kantor Cabang Pembantu Ancol'],
            ['id_unit_kerja' => 396, 'nama' => 'Kantor Cabang Pembantu Bekasi'],
            ['id_unit_kerja' => 397, 'nama' => 'Kantor Cabang Pembantu Bendungan Hilir'],
            ['id_unit_kerja' => 398, 'nama' => 'Kantor Cabang Pembantu Bintara'],
            ['id_unit_kerja' => 399, 'nama' => 'Kantor Cabang Pembantu Bintaro'],
            ['id_unit_kerja' => 400, 'nama' => 'Kantor Cabang Pembantu Bintaro Jaya'],
            ['id_unit_kerja' => 401, 'nama' => 'Kantor Cabang Pembantu Bogor'],
            ['id_unit_kerja' => 480, 'nama' => 'Kantor Cabang Pembantu BPN Jakarta Selatan'],
            ['id_unit_kerja' => 402, 'nama' => 'Kantor Cabang Pembantu Bumi Serpong Damai (BSD)'],
            ['id_unit_kerja' => 403, 'nama' => 'Kantor Cabang Pembantu Cakung'],
            ['id_unit_kerja' => 481, 'nama' => 'Kantor Cabang Pembantu Catatan Sipil'],
            ['id_unit_kerja' => 404, 'nama' => 'Kantor Cabang Pembantu Cempaka Mas'],
            ['id_unit_kerja' => 405, 'nama' => 'Kantor Cabang Pembantu Cibinong'],
            ['id_unit_kerja' => 406, 'nama' => 'Kantor Cabang Pembantu Cibubur'],
            ['id_unit_kerja' => 407, 'nama' => 'Kantor Cabang Pembantu Cikarang'],
            ['id_unit_kerja' => 408, 'nama' => 'Kantor Cabang Pembantu Cikini'],
            ['id_unit_kerja' => 409, 'nama' => 'Kantor Cabang Pembantu Cilandak'],
            ['id_unit_kerja' => 410, 'nama' => 'Kantor Cabang Pembantu Cinere'],
            ['id_unit_kerja' => 411, 'nama' => 'Kantor Cabang Pembantu Cipulir'],
            ['id_unit_kerja' => 412, 'nama' => 'Kantor Cabang Pembantu Cirendeu'],
            ['id_unit_kerja' => 483, 'nama' => 'Kantor Cabang Pembantu COne Plaza'],
            ['id_unit_kerja' => 413, 'nama' => 'Kantor Cabang Pembantu Daan Mogot'],
            ['id_unit_kerja' => 414, 'nama' => 'Kantor Cabang Pembantu Depok'],
            ['id_unit_kerja' => 415, 'nama' => 'Kantor Cabang Pembantu Dewi Sartika'],
            ['id_unit_kerja' => 484, 'nama' => 'Kantor Cabang Pembantu Dinas Koperasi UMKMP'],
            ['id_unit_kerja' => 485, 'nama' => 'Kantor Cabang Pembantu Dinas Lingkungan Hidup'],
            ['id_unit_kerja' => 486, 'nama' => 'Kantor Cabang Pembantu Dinas Penanggulangan Kebakaran dan Penyelamatan'],
            ['id_unit_kerja' => 416, 'nama' => 'Kantor Cabang Pembantu Dinas Pendidikan'],
            ['id_unit_kerja' => 612, 'nama' => 'Kantor Cabang Pembantu Disorla'],
            ['id_unit_kerja' => 417, 'nama' => 'Kantor Cabang Pembantu Fatmawati'],
            ['id_unit_kerja' => 418, 'nama' => 'Kantor Cabang Pembantu Glodok'],
            ['id_unit_kerja' => 487, 'nama' => 'Kantor Cabang Pembantu GMF Soekarno Hatta'],
            ['id_unit_kerja' => 419, 'nama' => 'Kantor Cabang Pembantu Green Pramuka'],
            ['id_unit_kerja' => 420, 'nama' => 'Kantor Cabang Pembantu Gunadarma'],
            ['id_unit_kerja' => 421, 'nama' => 'Kantor Cabang Pembantu Gunung Sahari'],
            ['id_unit_kerja' => 422, 'nama' => 'Kantor Cabang Pembantu Harapan Indah'],
            ['id_unit_kerja' => 424, 'nama' => 'Kantor Cabang Pembantu Jatibaru'],
            ['id_unit_kerja' => 425, 'nama' => 'Kantor Cabang Pembantu Jatiuwung'],
            ['id_unit_kerja' => 426, 'nama' => 'Kantor Cabang Pembantu Jelambar Baru'],
            ['id_unit_kerja' => 427, 'nama' => 'Kantor Cabang Pembantu Joglo'],
            ['id_unit_kerja' => 428, 'nama' => 'Kantor Cabang Pembantu Kalimalang'],
            ['id_unit_kerja' => 455, 'nama' => 'Kantor Cabang Pembantu Senen'],
            ['id_unit_kerja' => 429, 'nama' => 'Kantor Cabang Pembantu Karawaci'],
            ['id_unit_kerja' => 430, 'nama' => 'Kantor Cabang Pembantu Kawasan Berikat Nusantara'],
            ['id_unit_kerja' => 431, 'nama' => 'Kantor Cabang Pembantu Kebon Jeruk'],
            ['id_unit_kerja' => 488, 'nama' => 'Kantor Cabang Pembantu Kecamatan Cakung'],
            ['id_unit_kerja' => 489, 'nama' => 'Kantor Cabang Pembantu Kecamatan Cempaka Putih'],
            ['id_unit_kerja' => 490, 'nama' => 'Kantor Cabang Pembantu Kecamatan Cengkareng'],
            ['id_unit_kerja' => 491, 'nama' => 'Kantor Cabang Pembantu Kecamatan Cilandak'],
            ['id_unit_kerja' => 492, 'nama' => 'Kantor Cabang Pembantu Kecamatan Cilincing'],
            ['id_unit_kerja' => 493, 'nama' => 'Kantor Cabang Pembantu Kecamatan Cipayung'],
            ['id_unit_kerja' => 494, 'nama' => 'Kantor Cabang Pembantu Kecamatan Ciracas'],
            ['id_unit_kerja' => 495, 'nama' => 'Kantor Cabang Pembantu Kecamatan Duren Sawit'],
            ['id_unit_kerja' => 496, 'nama' => 'Kantor Cabang Pembantu Kecamatan Gambir'],
            ['id_unit_kerja' => 497, 'nama' => 'Kantor Cabang Pembantu Kecamatan Grogol Petamburan'],
            ['id_unit_kerja' => 498, 'nama' => 'Kantor Cabang Pembantu Kecamatan Jagakarsa'],
            ['id_unit_kerja' => 499, 'nama' => 'Kantor Cabang Pembantu Kecamatan Jatinegara'],
            ['id_unit_kerja' => 500, 'nama' => 'Kantor Cabang Pembantu Kecamatan Johar Baru'],
            ['id_unit_kerja' => 501, 'nama' => 'Kantor Cabang Pembantu Kecamatan Kalideres'],
            ['id_unit_kerja' => 502, 'nama' => 'Kantor Cabang Pembantu Kecamatan Kebayoran Baru'],
            ['id_unit_kerja' => 503, 'nama' => 'Kantor Cabang Pembantu Kecamatan Kebayoran Lama'],
            ['id_unit_kerja' => 504, 'nama' => 'Kantor Cabang Pembantu Kecamatan Kebon Jeruk'],
            ['id_unit_kerja' => 505, 'nama' => 'Kantor Cabang Pembantu Kecamatan Kelapa Gading'],
            ['id_unit_kerja' => 506, 'nama' => 'Kantor Cabang Pembantu Kecamatan Kemayoran'],
            ['id_unit_kerja' => 507, 'nama' => 'Kantor Cabang Pembantu Kecamatan Kembangan'],
            ['id_unit_kerja' => 508, 'nama' => 'Kantor Cabang Pembantu Kecamatan Koja'],
            ['id_unit_kerja' => 509, 'nama' => 'Kantor Cabang Pembantu Kecamatan Kramat Jati'],
            ['id_unit_kerja' => 510, 'nama' => 'Kantor Cabang Pembantu Kecamatan Makasar'],
            ['id_unit_kerja' => 511, 'nama' => 'Kantor Cabang Pembantu Kecamatan Mampang Prapatan'],
            ['id_unit_kerja' => 512, 'nama' => 'Kantor Cabang Pembantu Kecamatan Matraman'],
            ['id_unit_kerja' => 513, 'nama' => 'Kantor Cabang Pembantu Kecamatan Menteng'],
            ['id_unit_kerja' => 514, 'nama' => 'Kantor Cabang Pembantu Kecamatan Pademangan'],
            ['id_unit_kerja' => 515, 'nama' => 'Kantor Cabang Pembantu Kecamatan Palmerah'],
            ['id_unit_kerja' => 516, 'nama' => 'Kantor Cabang Pembantu Kecamatan Pancoran'],
            ['id_unit_kerja' => 517, 'nama' => 'Kantor Cabang Pembantu Kecamatan Pasar Minggu'],
            ['id_unit_kerja' => 518, 'nama' => 'Kantor Cabang Pembantu Kecamatan Pasar Rebo'],
            ['id_unit_kerja' => 519, 'nama' => 'Kantor Cabang Pembantu Kecamatan Penjaringan'],
            ['id_unit_kerja' => 520, 'nama' => 'Kantor Cabang Pembantu Kecamatan Pesanggrahan'],
            ['id_unit_kerja' => 521, 'nama' => 'Kantor Cabang Pembantu Kecamatan Pulo Gadung'],
            ['id_unit_kerja' => 522, 'nama' => 'Kantor Cabang Pembantu Kecamatan Sawah Besar'],
            ['id_unit_kerja' => 523, 'nama' => 'Kantor Cabang Pembantu Kecamatan Senen'],
            ['id_unit_kerja' => 524, 'nama' => 'Kantor Cabang Pembantu Kecamatan Setiabudi'],
            ['id_unit_kerja' => 525, 'nama' => 'Kantor Cabang Pembantu Kecamatan Taman Sari'],
            ['id_unit_kerja' => 526, 'nama' => 'Kantor Cabang Pembantu Kecamatan Tambora'],
            ['id_unit_kerja' => 527, 'nama' => 'Kantor Cabang Pembantu Kecamatan Tanah Abang'],
            ['id_unit_kerja' => 528, 'nama' => 'Kantor Cabang Pembantu Kecamatan Tanjung Priok'],
            ['id_unit_kerja' => 529, 'nama' => 'Kantor Cabang Pembantu Kecamatan Tebet'],
            ['id_unit_kerja' => 530, 'nama' => 'Kantor Cabang Pembantu Kedungdoro'],
            ['id_unit_kerja' => 432, 'nama' => 'Kantor Cabang Pembantu Kelapa Gading'],
            ['id_unit_kerja' => 433, 'nama' => 'Kantor Cabang Pembantu Kemang'],
            ['id_unit_kerja' => 434, 'nama' => 'Kantor Cabang Pembantu Klender'],
            ['id_unit_kerja' => 531, 'nama' => 'Kantor Cabang Pembantu KS Tubun'],
            ['id_unit_kerja' => 435, 'nama' => 'Kantor Cabang Pembantu Mampang Prapatan'],
            ['id_unit_kerja' => 436, 'nama' => 'Kantor Cabang Pembantu Mangga Besar (Krekot)'],
            ['id_unit_kerja' => 437, 'nama' => 'Kantor Cabang Pembantu Mangga Dua'],
            ['id_unit_kerja' => 438, 'nama' => 'Kantor Cabang Pembantu Mayestik'],
            ['id_unit_kerja' => 532, 'nama' => 'Kantor Cabang Pembantu MT.Haryono'],
            ['id_unit_kerja' => 439, 'nama' => 'Kantor Cabang Pembantu Muara Angke'],
            ['id_unit_kerja' => 533, 'nama' => 'Kantor Cabang Pembantu Nyi Ageng Serang'],
            ['id_unit_kerja' => 534, 'nama' => 'Kantor Cabang Pembantu PAM Jaya'],
            ['id_unit_kerja' => 440, 'nama' => 'Kantor Cabang Pembantu Pamulang'],
            ['id_unit_kerja' => 441, 'nama' => 'Kantor Cabang Pembantu Pantai Indah Kapuk'],
            ['id_unit_kerja' => 535, 'nama' => 'Kantor Cabang Pembantu Pasar Asem Reges'],
            ['id_unit_kerja' => 537, 'nama' => 'Kantor Cabang Pembantu Pasar Baru Bekasi'],
            ['id_unit_kerja' => 538, 'nama' => 'Kantor Cabang Pembantu Pasar Baru Metro Atom'],
            ['id_unit_kerja' => 540, 'nama' => 'Kantor Cabang Pembantu Pasar Bukit Duri'],
            ['id_unit_kerja' => 559, 'nama' => 'Kantor Cabang Pembantu Pasar Bunga Rawa Belong'],
            ['id_unit_kerja' => 542, 'nama' => 'Kantor Cabang Pembantu Pasar Cengkareng'],
            ['id_unit_kerja' => 543, 'nama' => 'Kantor Cabang Pembantu Pasar Cibinong'],
            ['id_unit_kerja' => 544, 'nama' => 'Kantor Cabang Pembantu Pasar Cibubur'],
            ['id_unit_kerja' => 545, 'nama' => 'Kantor Cabang Pembantu Pasar Cijantung'],
            ['id_unit_kerja' => 546, 'nama' => 'Kantor Cabang Pembantu Pasar Cikupa'],
            ['id_unit_kerja' => 547, 'nama' => 'Kantor Cabang Pembantu Pasar Cipete Utara'],
            ['id_unit_kerja' => 548, 'nama' => 'Kantor Cabang Pembantu Pasar Ciplak'],
            ['id_unit_kerja' => 549, 'nama' => 'Kantor Cabang Pembantu Pasar Cipulir'],
            ['id_unit_kerja' => 550, 'nama' => 'Kantor Cabang Pembantu Pasar Ciracas'],
            ['id_unit_kerja' => 552, 'nama' => 'Kantor Cabang Pembantu Pasar Induk Beras Cipinang'],
            ['id_unit_kerja' => 442, 'nama' => 'Kantor Cabang Pembantu Pasar Induk Kramat Jati'],
            ['id_unit_kerja' => 553, 'nama' => 'Kantor Cabang Pembantu Pasar Jati Asih'],
            ['id_unit_kerja' => 554, 'nama' => 'Kantor Cabang Pembantu Pasar Jatinegara'],
            ['id_unit_kerja' => 555, 'nama' => 'Kantor Cabang Pembantu Pasar Jembatan Lima'],
            ['id_unit_kerja' => 556, 'nama' => 'Kantor Cabang Pembantu Pasar Kalibaru'],
            ['id_unit_kerja' => 557, 'nama' => 'Kantor Cabang Pembantu Pasar Kebayoran Lama'],
            ['id_unit_kerja' => 558, 'nama' => 'Kantor Cabang Pembantu Pasar Kedoya'],
            ['id_unit_kerja' => 560, 'nama' => 'Kantor Cabang Pembantu Pasar Klender SS'],
            ['id_unit_kerja' => 561, 'nama' => 'Kantor Cabang Pembantu Pasar Koja Baru'],
            ['id_unit_kerja' => 562, 'nama' => 'Kantor Cabang Pembantu Pasar Kramat Jati'],
            ['id_unit_kerja' => 443, 'nama' => 'Kantor Cabang Pembantu Pasar Minggu'],
            ['id_unit_kerja' => 565, 'nama' => 'Kantor Cabang Pembantu Pasar Minggu 2'],
            ['id_unit_kerja' => 566, 'nama' => 'Kantor Cabang Pembantu Pasar Muara Karang'],
            ['id_unit_kerja' => 567, 'nama' => 'Kantor Cabang Pembantu Pasar Pademangan Timur'],
            ['id_unit_kerja' => 569, 'nama' => 'Kantor Cabang Pembantu Pasar Palmerah'],
            ['id_unit_kerja' => 568, 'nama' => 'Kantor Cabang Pembantu Pasar Pal Meriam'],
            ['id_unit_kerja' => 570, 'nama' => 'Kantor Cabang Pembantu Pasar Perumnas Klender'],
            ['id_unit_kerja' => 571, 'nama' => 'Kantor Cabang Pembantu Pasar Pramuka'],
            ['id_unit_kerja' => 572, 'nama' => 'Kantor Cabang Pembantu Pasar Pulo Gadung'],
            ['id_unit_kerja' => 573, 'nama' => 'Kantor Cabang Pembantu Pasar Rumput'],
            ['id_unit_kerja' => 574, 'nama' => 'Kantor Cabang Pembantu Pasar Santa'],
            ['id_unit_kerja' => 575, 'nama' => 'Kantor Cabang Pembantu Pasar Slipi'],
            ['id_unit_kerja' => 576, 'nama' => 'Kantor Cabang Pembantu Pasar Sunan Giri'],
            ['id_unit_kerja' => 577, 'nama' => 'Kantor Cabang Pembantu Pasar Sunter Podomoro'],
            ['id_unit_kerja' => 578, 'nama' => 'Kantor Cabang Pembantu Pasar Tanah Abang Blok A'],
            ['id_unit_kerja' => 579, 'nama' => 'Kantor Cabang Pembantu Pasar Tanah Abang Blok B'],
            ['id_unit_kerja' => 580, 'nama' => 'Kantor Cabang Pembantu Pasar Tebet Timur'],
            ['id_unit_kerja' => 581, 'nama' => 'Kantor Cabang Pembantu Pasar Teluk Gong'],
            ['id_unit_kerja' => 582, 'nama' => 'Kantor Cabang Pembantu Pasar Tomang'],
            ['id_unit_kerja' => 583, 'nama' => 'Kantor Cabang Pembantu Pasar UPB Kramat Jati'],
            ['id_unit_kerja' => 584, 'nama' => 'Kantor Cabang Pembantu PIK Pulogadung'],
            ['id_unit_kerja' => 585, 'nama' => 'Kantor Cabang Pembantu Plaza Baru Ciledug'],
            ['id_unit_kerja' => 444, 'nama' => 'Kantor Cabang Pembantu Pluit'],
            ['id_unit_kerja' => 445, 'nama' => 'Kantor Cabang Pembantu Pondok Gede'],
            ['id_unit_kerja' => 446, 'nama' => 'Kantor Cabang Pembantu Pondok Kelapa'],
            ['id_unit_kerja' => 447, 'nama' => 'Kantor Cabang Pembantu Pondok Labu'],
            ['id_unit_kerja' => 448, 'nama' => 'Kantor Cabang Pembantu Pondok Pinang'],
            ['id_unit_kerja' => 449, 'nama' => 'Kantor Cabang Pembantu Poris Daan Mogot'],
            ['id_unit_kerja' => 587, 'nama' => 'Kantor Cabang Pembantu PT Transportasi Jakarta'],
            ['id_unit_kerja' => 588, 'nama' => 'Kantor Cabang Pembantu Pulau Pramuka'],
            ['id_unit_kerja' => 450, 'nama' => 'Kantor Cabang Pembantu Pulogadung'],
            ['id_unit_kerja' => 589, 'nama' => 'Kantor Cabang Pembantu Pusdiklat PKP (Damkar)'],
            ['id_unit_kerja' => 451, 'nama' => 'Kantor Cabang Pembantu Rawa Belong'],
            ['id_unit_kerja' => 452, 'nama' => 'Kantor Cabang Pembantu Rawamangun'],
            ['id_unit_kerja' => 641, 'nama' => 'Kantor Cabang Pembantu RSKD Duren Sawit'],
            ['id_unit_kerja' => 590, 'nama' => 'Kantor Cabang Pembantu RS Tugu Ibu'],
            ['id_unit_kerja' => 591, 'nama' => 'Kantor Cabang Pembantu RSUD Cengkareng'],
            ['id_unit_kerja' => 592, 'nama' => 'Kantor Cabang Pembantu RSUD Koja'],
            ['id_unit_kerja' => 593, 'nama' => 'Kantor Cabang Pembantu RSUD Pasar Minggu'],
            ['id_unit_kerja' => 594, 'nama' => 'Kantor Cabang Pembantu RSUD Pasar Rebo'],
            ['id_unit_kerja' => 595, 'nama' => 'Kantor Cabang Pembantu RSUD Tarakan'],
            ['id_unit_kerja' => 596, 'nama' => 'Kantor Cabang Pembantu Rusun Kapuk Muara'],
            ['id_unit_kerja' => 597, 'nama' => 'Kantor Cabang Pembantu Rusun KS Tubun'],
            ['id_unit_kerja' => 598, 'nama' => 'Kantor Cabang Pembantu Rusun Marunda'],
            ['id_unit_kerja' => 599, 'nama' => 'Kantor Cabang Pembantu Rusun Muara Baru'],
            ['id_unit_kerja' => 600, 'nama' => 'Kantor Cabang Pembantu Rusun Nagrak'],
            ['id_unit_kerja' => 601, 'nama' => 'Kantor Cabang Pembantu Rusun Penjaringan'],
            ['id_unit_kerja' => 602, 'nama' => 'Kantor Cabang Pembantu Rusun Pesakih Daan Mogot'],
            ['id_unit_kerja' => 603, 'nama' => 'Kantor Cabang Pembantu Rusun Pinus Elok'],
            ['id_unit_kerja' => 604, 'nama' => 'Kantor Cabang Pembantu Rusun Pulogebang'],
            ['id_unit_kerja' => 606, 'nama' => 'Kantor Cabang Pembantu Rusun Rawabebek'],
            ['id_unit_kerja' => 605, 'nama' => 'Kantor Cabang Pembantu Rusun Rawa Buaya'],
            ['id_unit_kerja' => 607, 'nama' => 'Kantor Cabang Pembantu Rusun Rorotan'],
            ['id_unit_kerja' => 608, 'nama' => 'Kantor Cabang Pembantu Rusun Tambora'],
            ['id_unit_kerja' => 609, 'nama' => 'Kantor Cabang Pembantu Rusun Tipar Cakung'],
            ['id_unit_kerja' => 453, 'nama' => 'Kantor Cabang Pembantu Samsat Gunung Sahari'],
            ['id_unit_kerja' => 454, 'nama' => 'Kantor Cabang Pembantu Samsat Polda'],
            ['id_unit_kerja' => 610, 'nama' => 'Kantor Cabang Pembantu Samsat Timur'],
            ['id_unit_kerja' => 611, 'nama' => 'Kantor Cabang Pembantu Sidoarjo'],
            ['id_unit_kerja' => 456, 'nama' => 'Kantor Cabang Pembantu Sudirman'],
            ['id_unit_kerja' => 457, 'nama' => 'Kantor Cabang Pembantu Sunter'],
            ['id_unit_kerja' => 613, 'nama' => 'Kantor Cabang Pembantu Suryo Pranoto'],
            ['id_unit_kerja' => 458, 'nama' => 'Kantor Cabang Pembantu Syariah Bekasi'],
            ['id_unit_kerja' => 459, 'nama' => 'Kantor Cabang Pembantu Syariah Bintaro'],
            ['id_unit_kerja' => 460, 'nama' => 'Kantor Cabang Pembantu Syariah Bogor'],
            ['id_unit_kerja' => 461, 'nama' => 'Kantor Cabang Pembantu Syariah Cengkareng'],
            ['id_unit_kerja' => 462, 'nama' => 'Kantor Cabang Pembantu Syariah Cibubur'],
            ['id_unit_kerja' => 463, 'nama' => 'Kantor Cabang Pembantu Syariah Ciledug'],
            ['id_unit_kerja' => 464, 'nama' => 'Kantor Cabang Pembantu Syariah Ciputat'],
            ['id_unit_kerja' => 465, 'nama' => 'Kantor Cabang Pembantu Syariah Fatmawati'],
            ['id_unit_kerja' => 466, 'nama' => 'Kantor Cabang Pembantu Syariah Kelapa Gading'],
            ['id_unit_kerja' => 467, 'nama' => 'Kantor Cabang Pembantu Syariah Manggarai'],
            ['id_unit_kerja' => 468, 'nama' => 'Kantor Cabang Pembantu Syariah Margonda'],
            ['id_unit_kerja' => 469, 'nama' => 'Kantor Cabang Pembantu Syariah Matraman'],
            ['id_unit_kerja' => 642, 'nama' => 'Kantor Cabang Pembantu Syariah Pahlawan Revolusi'],
            ['id_unit_kerja' => 471, 'nama' => 'Kantor Cabang Pembantu Syariah Serpong'],
            ['id_unit_kerja' => 472, 'nama' => 'Kantor Cabang Pembantu Tanah Abang'],
            ['id_unit_kerja' => 473, 'nama' => 'Kantor Cabang Pembantu Tangerang'],
            ['id_unit_kerja' => 474, 'nama' => 'Kantor Cabang Pembantu Tebet Barat'],
            ['id_unit_kerja' => 614, 'nama' => 'Kantor Cabang Pembantu Terminal Terpadu Pulo Gebang'],
            ['id_unit_kerja' => 615, 'nama' => 'Kantor Cabang Pembantu Thamrin City'],
            ['id_unit_kerja' => 475, 'nama' => 'Kantor Cabang Pembantu Tomang'],
            ['id_unit_kerja' => 616, 'nama' => 'Kantor Cabang Pembantu Tropodo'],
            ['id_unit_kerja' => 617, 'nama' => 'Kantor Cabang Pembantu Univ. Gunadarma Cengkareng'],
            ['id_unit_kerja' => 618, 'nama' => 'Kantor Cabang Pembantu Univ. Gunadarma Kalimalang'],
            ['id_unit_kerja' => 619, 'nama' => 'Kantor Cabang Pembantu Univ. Gunadarma Karawaci'],
            ['id_unit_kerja' => 620, 'nama' => 'Kantor Cabang Pembantu Univ. Gunadarma Salemba'],
            ['id_unit_kerja' => 621, 'nama' => 'Kantor Cabang Pembantu UPB Mayestik'],
            ['id_unit_kerja' => 622, 'nama' => 'Kantor Cabang Pembantu UPB Senen Blok III'],
            ['id_unit_kerja' => 623, 'nama' => 'Kantor Cabang Pembantu UPPRD Cipayung'],
            ['id_unit_kerja' => 624, 'nama' => 'Kantor Cabang Pembantu UPPRD Ciracas'],
            ['id_unit_kerja' => 476, 'nama' => 'Kantor Cabang Pembantu Utan Kayu'],
            ['id_unit_kerja' => 477, 'nama' => 'Kantor Cabang Pembantu Walikota Jakarta Pusat'],
            ['id_unit_kerja' => 479, 'nama' => 'Kantor Cabang Pembantu Warung Jati'],
            ['id_unit_kerja' => 626, 'nama' => 'Kantor Cabang Pembantu YPI Bahrul Ulum'],
            ['id_unit_kerja' => 382, 'nama' => 'Kantor Cabang Permata Hijau'],
            ['id_unit_kerja' => 383, 'nama' => 'Kantor Cabang Pintu Besar Selatan'],
            ['id_unit_kerja' => 389, 'nama' => 'Kantor Cabang Slamet Riyadi'],
            ['id_unit_kerja' => 391, 'nama' => 'Kantor Cabang Syariah Bandung'],
            ['id_unit_kerja' => 646, 'nama' => 'Kantor Cabang Syariah Pondok Indah'],
            ['id_unit_kerja' => 384, 'nama' => 'Kantor Cabang Tanjung Priok'],
            ['id_unit_kerja' => 376, 'nama' => 'Kantor Cabang Utama Balaikota'],
            ['id_unit_kerja' => 377, 'nama' => 'Kantor Cabang Utama Syariah Wahid Hasyim'],
            ['id_unit_kerja' => 385, 'nama' => 'Kantor Cabang Walikota Jakarta Barat'],
            ['id_unit_kerja' => 644, 'nama' => 'Kantor Cabang Walikota Jakarta Pusat'],
            ['id_unit_kerja' => 386, 'nama' => 'Kantor Cabang Walikota Jakarta Selatan'],
            ['id_unit_kerja' => 387, 'nama' => 'Kantor Cabang Walikota Jakarta Timur'],
            ['id_unit_kerja' => 645, 'nama' => 'Kantor Cabang Walikota Jakarta Utara'],
            ['id_unit_kerja' => 627, 'nama' => 'Kantor Kas Syariah Asshidiqiyah (Kedoya)'],
            ['id_unit_kerja' => 628, 'nama' => 'Kantor Kas Syariah Assidiqiyah Batu Ceper'],
            ['id_unit_kerja' => 629, 'nama' => 'Kantor Kas Syariah Cikarang'],
            ['id_unit_kerja' => 630, 'nama' => 'Kantor Kas Syariah Johar Baru'],
            ['id_unit_kerja' => 647, 'nama' => 'Kantor Kas Syariah Kranggan'],
            ['id_unit_kerja' => 632, 'nama' => 'Kantor Kas Syariah Pondok Karya Pembangunan'],
            ['id_unit_kerja' => 22, 'nama' => 'Komisaris'],
            ['id_unit_kerja' => 251, 'nama' => 'PT. Darbeni Bangun Karya'],
            ['id_unit_kerja' => 359, 'nama' => 'Sekretaris Perusahaan'],
            ['id_unit_kerja' => 643, 'nama' => 'Senior Executive Vice President (SEVP)'],
            ['id_unit_kerja' => 120, 'nama' => 'Staff Ahli'],
            ['id_unit_kerja' => 372, 'nama' => 'Tim Transformasi Bank DKI'],
        ];

        collect($collections)->each(function ($data) {
            UnitKerja::create($data);
        });
    }
}
