<?php

namespace Database\Seeders;

use App\Models\UnitKerja;
use Illuminate\Database\Seeder;

class UnitKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $collections = [
            ['nama' => 'Grup Teknologi Informasi', 'singkatan' => 'TSI'],
            ['nama' => 'Grup Sumber Daya Manusia', 'singkatan' => 'SDM'],
            ['nama' => 'Grup Pengadaan & Pengelolaan Aset', 'singkatan' => 'PPA'],
            ['nama' => 'Grup Akuntansi & Keuangan', 'singkatan' => 'AKT'],
            ['nama' => 'Grup Tresuri', 'singkatan' => 'TRS'],
            ['nama' => 'Grup Kredit Konsumer', 'singkatan' => 'KKS'],
            ['nama' => 'Grup Audit Internal', 'singkatan' => 'SKAI'],
            ['nama' => 'Sekretaris Perusahaan', 'singkatan' => 'CORSEC'],
            ['nama' => 'Grup Manajemen Risiko', 'singkatan' => 'MRI'],
            ['nama' => 'Grup Kepatuhan', 'singkatan' => 'KPT'],
            ['nama' => 'Grup Hukum', 'singkatan' => 'HKM'],
            ['nama' => 'Grup Kredit Mikro', 'singkatan' => 'KMI'],
            ['nama' => 'Grup Kredit Menengah', 'singkatan' => 'KMN'],
            ['nama' => 'Grup Bisnis Digital', 'singkatan' => 'DIG'],
            ['nama' => 'Grup Risiko Kredit', 'singkatan' => 'RKT'],
            ['nama' => 'Grup Restrukturisasi Kredit dan Penyelesaian Kredit Bermasalah', 'singkatan' => 'RPK'],
            ['nama' => 'Grup Operasional', 'singkatan' => 'OPS'],
            ['nama' => 'Grup Pengembangan Jaringan', 'singkatan' => 'JAR'],
            ['nama' => 'Grup Perencanaan Strategis & Kinerja', 'singkatan' => 'RENSTRA'],
            ['nama' => 'Grup Kebijakan & Prosedur', 'singkatan' => 'KEB'],
            ['nama' => 'Grup Hubungan Kelembagaan', 'singkatan' => 'HBL'],
            ['nama' => 'Grup Administrasi Kredit & Pembiayaan', 'singkatan' => 'ADK'],
            ['nama' => 'Grup Penjualan Dana & Transaksional', 'singkatan' => 'PDT'],
            ['nama' => 'Dana Pensiun Bank DKI', 'singkatan' => 'DPBD'],
            ['nama' => 'Dewan Pengawas Syariah', 'singkatan' => 'DPS'],
            ['nama' => 'Direksi', 'singkatan' => 'DIR'],
            ['nama' => 'Grup Kredit Komersial', 'singkatan' => 'KKM'],
            ['nama' => 'Grup Kredit Ritel', 'singkatan' => 'KRI'],
            ['nama' => 'Grup Syariah', 'singkatan' => 'SYA'],
            ['nama' => 'Kantor Cabang Bandung', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Gresik', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Juanda', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Kebayoran Baru', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Matraman', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Otista', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Pembantu Abdul Muis', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Alam Sutera', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Ambengan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Ancol', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Badan Pertanahan Nasional Jakarta Selatan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Bekasi', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Bendungan Hilir', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Bintara', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Bintaro', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Bintaro Jaya', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Bogor', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu BSD', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu BPN Jakarta Selatan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cakung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Catatan Sipil', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cempaka Mas', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cibinong', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cibubur', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cikarang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cikini', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cilandak', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cinere', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cipinang Elok', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cipulir', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Cirendeu', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu COne Plaza', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Daan Mogot', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Depok', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Dewi Sartika', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Dinas Koperasi UMKMP', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Dinas Lingkungan Hidup', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Dinas Penanggulangan Kebakaran dan Penyelamatan (PKP)', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Dinas Pendidikan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Disorla', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Fatmawati', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Glodok', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu GMF Soekarno Hatta', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Green Pramuka', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Gunadarma', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Gunung Sahari', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Harapan Indah', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Jababeka', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Jatibaru', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Jatiuwung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Jelambar Baru', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Joglo', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kalimalang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Karawaci', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kawasan Berikat Nusantara', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kebon Jeruk', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Cakung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Cempaka Putih', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Cengkareng', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Cilandak', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Cilincing', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Cipayung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Ciracas', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Duren Sawit', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Gambir', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Grogol Petamburan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Jagakarsa', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Jatinegara', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Johar Baru', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Kalideres', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Kebayoran Baru', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Kebayoran Lama', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Kebon Jeruk', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Kelapa Gading', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Kemayoran', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Kembangan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Koja', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Kramat Jati', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Makasar', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Mampang Prapatan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Matraman', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Menteng', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Pademangan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Palmerah', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Pancoran', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Pasar Minggu', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Pasar Rebo', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Penjaringan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Pesanggrahan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Pulo Gadung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Sawah Besar', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Senen', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Setiabudi', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Taman Sari', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Tambora', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Tanah Abang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Tanjung Priok', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kecamatan Tebet', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kedungdoro', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kelapa Gading', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Kemang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Klender', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu KS Tubun', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Mampang Prapatan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Mangga Besar (Krekot)', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Mangga Dua', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Mayestik', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu MT.Haryono', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Muara Angke', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Nyi Ageng Serang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu PAM Jaya', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pamulang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pantai Indah Kapuk', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Asam Reges', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Baru Bantar Gebang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Baru Bekasi', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Baru Metro Atom', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Bata Putih', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Blok M Square', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Bukit Duri', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Bunga Rawa Belong', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Ceger Pondok Aren', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Cengkareng', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Cibinong', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Cibubur', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Cijantung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Cikupa', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Cipete Utara', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Ciplak', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Cipulir', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Ciracas', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Enjo', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Induk Beras Cipinang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Induk Kramat Jati', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Jati Asih', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Jatinegara', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Jembatan Lima', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Kalibaru', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Kebayoran Lama', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Kedoya Barat', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Kembang Rawa Belong', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Klender SS', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Koja Baru', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Kramat Jati', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Kranggan Mas', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Malabar', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Minggu', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Minggu 2', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Muara Karang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Pademangan Timur', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Pal Meriam', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Palmerah', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Perumnas Klender', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Pramuka', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Pulo Gadung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Rumput', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Santa', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Slipi', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Sunan Giri', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Sunter Podomoro', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Tanah Abang Blok A', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Tanah Abang Blok B', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Tebet Timur', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Teluk Gong', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar Tomang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pasar UPB Kramat Jati', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu PIK Pulogadung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Plaza Baru Ciledug', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Plaza Blok M Square', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pluit', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pondok Gede', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pondok Kelapa', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pondok Labu', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pondok Pinang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Poris Daan Mogot', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu PT Transportasi Jakarta', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pulau Pramuka', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pulogadung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Pusdiklat PKP', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rawa Belong', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rawamangun', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu RSKD Duren Sawit', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu RS Tugu Ibu', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu RSUD Cengkareng', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu RSUD Koja', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu RSUD Pasar Minggu', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu RSUD Pasar Rebo', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu RSUD Tarakan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Kapuk Muara', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun KS Tubun', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Marunda', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Muara Baru', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Nagrak', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Penjaringan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Pesakih Daan Mogot', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Pinus Elok', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Pulogebang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Rawa Buaya', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Rawabebek', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Rorotan', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Tambora', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Rusun Tipar Cakung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Samsat Gunung Sahari', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Samsat POLDA', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Samsat Timur', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Senen', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Sidoarjo', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Sudin PU Jakarta Timur', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Sudirman', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Sunter', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Suryopranoto', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Bekasi', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Bintaro', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Bogor', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Cengkareng', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Cibubur', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Ciledug', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Ciputat', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Fatmawati', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Kelapa Gading', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Manggarai', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Margonda', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Matraman', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Pahlawan Revolusi', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Pondok Indah', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Syariah Serpong', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Tanah Abang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Tangerang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Tebet Barat', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Terminal Terpadu Pulo Gebang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Thamrin City', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Tomang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Tropodo', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Universitas Gunadarma Cengkareng', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Universitas Gunadarma Kalimalang', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Universitas Gunadarma Karawaci', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Universitas Gunadarma Salemba', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu UPB Mayestik', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu UPB Senen Blok III', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu UPPRD Cipayung', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu UPPRD Ciracas', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Utan Kayu', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Walikota Jakarta Pusat', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Walikota Jakarta Utara', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu Warung Jati', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Pembantu YPI Bahrul Ulum', 'singkatan' => 'KCP'],
            ['nama' => 'Kantor Cabang Permata Hijau', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Pintu Besar Selatan', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Slamet Riyadi', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Syariah Bandung', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Syariah Pondok Indah', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Tanjung Priok', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Utama Balaikota', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Utama Syariah Wahid Hasyim', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Walikota Jakarta Barat', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Walikota Jakarta Pusat', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Walikota Jakarta Selatan', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Walikota Jakarta Timur', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Cabang Walikota Jakarta Utara', 'singkatan' => 'KC'],
            ['nama' => 'Kantor Kas Syariah Asshidiqiyah (Kedoya)', 'singkatan' => 'KK'],
            ['nama' => 'Kantor Kas Syariah Assidiqiyah Batu Ceper', 'singkatan' => 'KK'],
            ['nama' => 'Kantor Kas Syariah Cikarang', 'singkatan' => 'KK'],
            ['nama' => 'Kantor Kas Syariah Johar Baru', 'singkatan' => 'KK'],
            ['nama' => 'Kantor Kas Syariah Pahlawan Revolusi', 'singkatan' => 'KK'],
            ['nama' => 'Kantor Kas Syariah Pondok Karya Pembangunan', 'singkatan' => 'KK'],
            ['nama' => 'Komisaris', 'singkatan' => 'KOM'],
            ['nama' => 'PT. Darbeni Bangun Karya', 'singkatan' => 'DRB'],
            ['nama' => 'Senior Executive Vice President (SEVP)', 'singkatan' => 'STA'],
            ['nama' => 'Staff Ahli', 'singkatan' => 'STA'],
            ['nama' => 'Tim Transformasi Bank DKI', 'singkatan' => 'TRA'],
        ];

        collect($collections)->each(function ($data) {
            UnitKerja::create($data);
        });
    }
}
